### ISSUE TITLE
Problem adding custom component. 

### ISSUE THREAD

**Issue by wachux** [PiotrMachowski/Home-Assistant-custom-components-Looko2#4]
Cześć,

Mam problem z dodaniem tego do HA. Wpis w configuration.yaml:
  - platform: looko2
    api_key: my_token
    name: LookO2
    station_id: 'SEMAFOROWA_79'
    monitored_conditions:
      - 'Color'
      - 'IJP'
      - 'IJPDescription'
      - 'IJPDescriptionEN'
      - 'IJPString'
      - 'IJPStringEN'
      - 'PM10'
      - 'PM25'

Błąd w logu podczas startowania HA:

2020-04-06 12:50:51 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up looko2 platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/looko2/sensor.py", line 59, in setup_platform
    raise Exception('Invalid configuration for LookO2 platform')
Exception: Invalid configuration for LookO2 platform

**Comment by wachux** [comment]
OK, problem rozwiązany - spostrzegawczy sąsiad mi napisał że mam złe ID. Po zmianie wszystko działa.

**Comment by kpietrek** [comment]
Jak uzyskać api_key? Podpowiecie?

**Comment by PiotrMachowski** [comment]
https://looko2web.nazwa.pl/aktualnosci/api/

**Comment by kpietrek** [comment]
Rozumiem, że muszę do nich napisać maila? Tak?

**Comment by PiotrMachowski** [comment]
> Aby poprawnie korzystać z API, potrzebny jest klucz, który należy podać do argumentu &token. Skontaktuj się z nami by go uzyskać – kontakt@looko2.com
