### ISSUE TITLE
Problem z dłuższymi opisami

### ISSUE THREAD

**Issue by ryrzy** [PiotrMachowski/Home-Assistant-custom-components-Looko2#7]
Wygląda na to, że jest problem z dłuższymi opisami jakości powietrza (chyba, że to jakiś problem z bazą u mnie?)

```
Logger: homeassistant.components.sensor
Source: core.py:871
Integration: Sensor (documentation, issues)
First occurred: 1 grudnia 2020, 21:13:39 (2 occurrences)
Last logged: 1 grudnia 2020, 21:13:39

Error adding entities for domain sensor with platform looko2
Error while setting up looko2 platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 316, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 531, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 408, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1185, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 871, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity id: sensor.looko2_xxx_1_ijpdescription. State max length is 255 characters.
```

**Comment by PiotrMachowski** [comment]
Jakiej bazy używasz?

**Comment by ryrzy** [comment]
MariaDB

**Comment by ryrzy** [comment]
;>

**Comment by PiotrMachowski** [comment]
Fixed in [v2.0.0](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Looko2/releases/tag/v2.0.0)
